stockly-postgresql:
  container_name: stockly-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/stockly/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=stockly
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
